import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

const read = (path) => readFileSync(new URL(`../${path}`, import.meta.url), 'utf8');
const provider = read('lib/health/pedometer-provider.ts');
const service = read('lib/health/health-service.ts');
const hook = read('hooks/use-phone-activity.ts');
const home = read('app/(tabs)/home.tsx');
const schedule = read('app/(tabs)/appointments.tsx');
const profile = read('app/(tabs)/profile.tsx');
const ai = read('lib/services/ai-care.ts');

test('Pedometer availability and permission are checked', () => { assert.match(provider, /isAvailableAsync/); assert.match(provider, /getPermissionsAsync/); assert.match(provider, /requestPermissionsAsync/); });
test('today query starts at local midnight and maps real steps', () => { assert.match(provider, /new Date\(value\.getFullYear\(\), value\.getMonth\(\), value\.getDate\(\)\)/); assert.match(provider, /getStepCountAsync\(localStartOfDay\(date\), new Date\(\)\)/); });
test('missing readings stay null rather than fake zero', () => { assert.match(provider, /steps: null/); assert.doesNotMatch(provider, /steps:\s*0/); });
test('one shared listener cleans up when the last subscriber leaves', () => { assert.match(service, /if \(!activeCleanup\)/); assert.match(service, /activeCleanup\?\.\(\)/); assert.match(service, /subscriberCount === 0/); assert.match(hook, /subscribeToLiveSteps/); });
test('manual planned activity remains separate and is not auto completed', () => { assert.match(schedule, /PLANNED ACTIVITIES/); assert.match(schedule, /setActivityStatus/); assert.doesNotMatch(service, /setActivityStatus|activity_logs|supabase/); });
test('Home displays device activity without fake walking duration', () => { assert.match(home, /TODAY&apos;S ACTIVITY/); assert.match(home, /Source: This device/); assert.doesNotMatch(home, /phoneActivity.*minutes/); });
test('Profile exposes honest connected health states', () => { assert.match(profile, /Connected Health/); assert.match(profile, /Phone Activity/); assert.match(profile, /Not Connected/); assert.doesNotMatch(profile, /Development Build Required/); });
test('provider abstraction prepares Apple Health and Health Connect', () => { const types=read('lib/health/types.ts'); assert.match(types, /HealthProvider/); assert.match(types, /apple_health/); assert.match(types, /health_connect/); });
test('AI adds only minimal device activity context for relevant explicit prompts', () => { assert.match(ai, /asksAboutActivity/); assert.match(ai, /activity_context/); assert.match(ai, /steps\s*:\s*activity\.steps\s*,\s*source\s*:\s*activity\.source/); });
test('new UI consumes live theme tokens', () => { assert.match(home, /theme\.cardBg|SurfaceCard/); assert.match(schedule, /theme\.cardBg/); assert.match(profile, /theme\.textPrimary/); });
test('Care Calendar remains outside Phase 5 implementation', () => { assert.doesNotMatch(service, /care-calendar/); });
test('permission is requested only from explicit connect action',()=>{const daily=provider.slice(provider.indexOf('getDailyActivity'),provider.indexOf('requestPermission'));assert.doesNotMatch(daily,/requestPermissionsAsync/);assert.match(service,/connectPhoneActivity/);assert.match(read('components/phone-activity-permission-modal.tsx'),/Allow Motion &amp; Fitness/)});
test('phone activity opt-in is account scoped even when iOS permission is already granted',()=>{assert.match(service,/genie_cares_phone_activity_connected:\$\{userId\}/);assert.match(service,/setActiveUser/);assert.match(service,/publish\(null/);assert.match(hook,/setActiveUser\(user\?\.id/);});
test('Home Schedule and Activity Details share the normalized store',()=>{assert.match(home,/usePhoneActivity/);assert.match(schedule,/usePhoneActivity/);assert.match(read('app/device-activity.tsx'),/usePhoneActivity/);assert.match(hook,/useSyncExternalStore/)});
test('History provides search and type filtering without history date heading',()=>{assert.match(schedule,/Search records/);assert.match(schedule,/Filtered Records/);assert.match(schedule,/historyType/);assert.doesNotMatch(schedule,/History for/)});
test('Genie empty chat uses sentence suggestions and full conversation layout',()=>{const chat=read('app/(tabs)/assistant.tsx');assert.match(chat,/Hello\. I&apos;m Genie, your AI care assistant/);assert.match(chat,/How active was I today/);assert.match(chat,/KeyboardAvoidingView/);assert.match(chat,/messageList: \{ flex: 1/)});
test('profile save is authenticated owner filtered and normalizes phone fields',()=>{const profileService=read('lib/services/profile.ts');assert.match(profileService,/getUser/);assert.match(profileService,/\.eq\('user_id', userId\)/);assert.match(profileService,/emergency_contact_phone/);assert.match(profileService,/normalizePhone/)});
test('dedicated connected health and device activity screens exist',()=>{assert.match(read('app/connected-health.tsx'),/Connected Health/);assert.match(read('app/device-activity.tsx'),/Activity &amp; Steps/)});
test('device activity replaces the broken dash with explicit no-reading states and actions',()=>{const screen=read('app/device-activity.tsx');assert.doesNotMatch(screen,/â€”/);assert.match(screen,/Connect Phone Activity to display your steps/);assert.match(screen,/Open Device Settings/);assert.match(screen,/Refresh Steps/);});
test('local notification responses use Expo Router destinations',()=>{const navigation=read('providers/notification-navigation-provider.tsx');assert.match(navigation,/addNotificationResponseReceivedListener/);assert.match(navigation,/appointment-details/);assert.match(navigation,/\(tabs\)\/appointments/)});
test('external store snapshots are referentially stable',()=>{assert.match(service,/let currentState: PhoneActivityState = SERVER_STATE/);assert.match(service,/getState: \(\) => currentState/);assert.doesNotMatch(service,/getState: \(\) => \(\{/)});
test('server snapshot is a stable frozen constant',()=>{assert.match(service,/const SERVER_STATE[^\n]*Object\.freeze/);assert.match(service,/getServerState: \(\) => SERVER_STATE/);assert.match(hook,/healthService\.getServerState/)});
test('snapshot reads are pure and updates are change aware',()=>{const getter=service.slice(service.indexOf('getState:'),service.indexOf('getServerState:'));assert.doesNotMatch(getter,/refresh|Pedometer|forEach/);assert.match(service,/if \(sameSnapshot[\s\S]*sameStatus[\s\S]*return currentState/)});
test('subscribe and unsubscribe do not synchronously notify',()=>{const subscribe=service.slice(service.indexOf('subscribeState'),service.indexOf('refresh:'));assert.match(subscribe,/stateSubscribers\.add\(listener\)/);assert.match(subscribe,/stateSubscribers\.delete\(listener\)/);assert.doesNotMatch(subscribe,/listener\(\)/)});
test('shared watcher has first-consumer start and last-consumer cleanup',()=>{assert.match(service,/if \(!activeCleanup\)/);assert.match(service,/subscriberCount === 0/);assert.match(service,/activeCleanup\?\.\(\)/);assert.equal((service.match(/subscribeToSteps\?\./g)||[]).length,1)});
test('unchanged refresh does not notify and changed steps publish once',()=>{assert.match(service,/sameSnapshot/);assert.match(service,/sameStatus/);assert.match(service,/publish\(\{ \.\.\.snapshot, steps: liveBaselineSteps \+ steps/)});
