import MaterialIcons from '@expo/vector-icons/MaterialIcons';
import { useFocusEffect } from '@react-navigation/native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useCallback, useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { ErrorState, LoadingState, ScreenContainer } from '@/components/ui/screen-states';
import { Brand } from '@/constants/theme';
import { getActivityAdherence, getActivityDetails, setActivityStatus } from '@/lib/services/activities';
import { canConfirmActivity } from '@/lib/care-action-windows';
import type { ActivityLog } from '@/types';

export default function ActivityDetails(){const{id}=useLocalSearchParams<{id:string}>(),router=useRouter(),[activity,setActivity]=useState<ActivityLog|null>(null),[adherence,setAdherence]=useState<{due:number;completed:number;percentage:number|null}|null>(null),[error,setError]=useState('');const load=useCallback(()=>{setError('');const end=new Date(),start=new Date();start.setDate(start.getDate()-29);Promise.all([getActivityDetails(id),getActivityAdherence(start.toISOString(),end.toISOString())]).then(([item,recent])=>{setActivity(item);setAdherence(recent)}).catch(()=>setError('Activity not found.'))},[id]);useFocusEffect(useCallback(()=>{load()},[load]));if(error)return <ErrorState message={error} onRetry={load}/>;if(!activity)return <LoadingState label="Loading activity..."/>;const status=async(next:'completed'|'skipped')=>{try{await setActivityStatus(id,next);load()}catch{Alert.alert('Could Not Update Activity','Please try again.')}};return <ScreenContainer contentContainerStyle={s.content}><View style={s.header}><Pressable accessibilityLabel="Go back" onPress={()=>router.back()}><MaterialIcons name="arrow-back" size={24} color={Brand.primary}/></Pressable><Text style={s.title}>Activity Details</Text></View><View style={s.banner}><Text style={s.bannerTitle}>{activity.activityType}</Text><Text style={s.bannerText}>{new Date(activity.startedAt).toLocaleString()}</Text><Text style={s.bannerText}>{activity.status.toUpperCase()}</Text></View><View style={s.card}><Row label="Duration" value={activity.durationMinutes===null?'Not specified':`${activity.durationMinutes} minutes`}/><Row label="Distance" value={activity.distanceKm===null?'Not specified':`${activity.distanceKm} km`}/><Row label="Steps" value={activity.steps===null?'Not specified':String(activity.steps)}/><Row label="Repeats" value={activity.recurrence}/><Row label="Notes" value={activity.notes??'None'}/></View><View style={s.card}><Text style={s.adherence}>{adherence?.percentage===null||adherence===null?'No activity adherence yet':`${adherence.percentage}% recent adherence`}</Text><Text style={s.note}>{adherence?.completed??0} of {adherence?.due??0} due activities completed in the last 30 days.</Text></View>{activity.status==='scheduled'&&canConfirmActivity(activity.startedAt)?<><Pressable style={s.primary} onPress={()=>status('completed')}><Text style={s.white}>Complete</Text></Pressable><Pressable style={s.outline} onPress={()=>status('skipped')}><Text style={s.link}>Skip</Text></Pressable></>:activity.status==='scheduled'?<Text style={s.note}>Upcoming activities can be completed or skipped after their planned start.</Text>:null}<Pressable style={s.outline} onPress={()=>router.push({pathname:'/add-activity',params:{id}})}><Text style={s.link}>Edit This Activity</Text></Pressable><Text style={s.note}>Completion is recorded per scheduled occurrence so recurring-activity adherence remains accurate.</Text></ScreenContainer>}
function Row({label,value}:{label:string;value:string}){return <View><Text style={s.label}>{label}</Text><Text style={s.value}>{value}</Text></View>}
const s=StyleSheet.create({content:{padding:18,gap:14,backgroundColor:Brand.screenBg},header:{minHeight:44,flexDirection:'row',alignItems:'center',gap:12},title:{fontSize:25,fontWeight:'700',color:Brand.primary},banner:{padding:20,gap:5,borderRadius:16,backgroundColor:Brand.bannerBackground},bannerTitle:{fontSize:24,fontWeight:'700',color:'#FFF'},bannerText:{color:'rgba(255,255,255,.86)'},card:{padding:18,gap:14,borderRadius:14,backgroundColor:'#FFF',borderWidth:1,borderColor:Brand.cardBorder},label:{fontSize:11,fontWeight:'700',color:Brand.textSecondary},value:{color:Brand.textPrimary,marginTop:3},adherence:{fontSize:22,fontWeight:'700',color:Brand.primary},primary:{padding:16,borderRadius:12,alignItems:'center',backgroundColor:Brand.primaryButtonBackground},white:{color:'#FFF',fontWeight:'700'},outline:{padding:15,borderRadius:12,alignItems:'center',borderWidth:1,borderColor:Brand.secondary},link:{color:Brand.secondary,fontWeight:'700'},note:{fontSize:12,lineHeight:18,color:Brand.textSecondary}});
