import MaterialIcons from '@expo/vector-icons/MaterialIcons';
import { useFocusEffect } from '@react-navigation/native';
import { useRouter } from 'expo-router';
import { useCallback, useMemo, useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { EmptyState, LoadingState, ScreenContainer } from '@/components/ui/screen-states';
import { usePalette, type ThemePalette } from '@/hooks/use-palette';
import { getNotifications, markAllNotificationsRead, markNotificationRead } from '@/lib/services/notifications';
import type { InAppNotification } from '@/types';

export default function Notifications(){
 const router=useRouter(),theme=usePalette(),styles=useMemo(()=>makeStyles(theme),[theme]),[data,setData]=useState<InAppNotification[]|null>(null),[error,setError]=useState(''),[updating,setUpdating]=useState(false);
 const load=useCallback(async()=>{setError('');try{setData(await getNotifications());}catch(loadError){if(__DEV__)console.debug('[Notifications] Failed to load',{name:loadError instanceof Error?loadError.name:'UnknownError',message:loadError instanceof Error?loadError.message:'Unknown failure'});setError(loadError instanceof Error?loadError.message:'Could not load notifications.');}},[]);
 useFocusEffect(useCallback(()=>{void load();},[load]));
 const goBack=()=>router.canGoBack()?router.back():router.replace('/(tabs)/home');
 const open=async(notification:InAppNotification)=>{try{if(!notification.readAt){const updated=await markNotificationRead(notification.id);setData(current=>current?.map(item=>item.id===updated.id?updated:item)??null);}if(notification.appointmentId)router.push({pathname:'/appointment-details',params:{id:notification.appointmentId}});else if(notification.medicationLogId)router.push('/(tabs)/appointments');}catch(actionError){Alert.alert('Could Not Open Notification',actionError instanceof Error?actionError.message:'Please try again.');}};
 const markAll=async()=>{if(updating)return;setUpdating(true);try{await markAllNotificationsRead();setData(current=>current?.map(item=>({...item,readAt:item.readAt??new Date().toISOString()}))??null);}catch(actionError){Alert.alert('Could Not Update Notifications',actionError instanceof Error?actionError.message:'Please try again.');}finally{setUpdating(false);}};
 return <ScreenContainer contentContainerStyle={styles.content}><View style={styles.header}><View style={styles.headerLeft}><Pressable accessibilityLabel="Go back" hitSlop={10} onPress={goBack}><MaterialIcons name="arrow-back" size={24} color={theme.primary}/></Pressable><Text style={styles.title}>Notifications</Text></View>{data?.some(item=>!item.readAt)?<Pressable accessibilityRole="button" disabled={updating} onPress={()=>void markAll()}><Text style={styles.mark}>{updating?'Updating...':'Mark all as read'}</Text></Pressable>:null}</View>
  {data===null&&!error?<LoadingState label="Loading notifications..."/>:error?<View accessibilityRole="alert" style={styles.error}><Text style={styles.errorTitle}>{error}</Text><Pressable style={styles.retry} onPress={load}><Text style={styles.retryText}>Try Again</Text></Pressable></View>:!data?.length?<EmptyState message="No notifications yet."/>:data.map(notification=><Pressable key={notification.id} style={[styles.card,!notification.readAt&&styles.unread]} onPress={()=>open(notification)}><View style={styles.flex}><Text style={styles.cardTitle}>{notification.title}</Text><Text style={styles.body}>{notification.body}</Text><Text style={styles.time}>{new Date(notification.createdAt).toLocaleString()}</Text></View>{!notification.readAt?<View style={styles.dot}/>:null}</Pressable>)}
 </ScreenContainer>;
}
const makeStyles=(theme:ThemePalette)=>StyleSheet.create({content:{paddingHorizontal:18,paddingTop:20,gap:12,backgroundColor:theme.screenBg},header:{minHeight:48,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},headerLeft:{flexDirection:'row',alignItems:'center',gap:12},title:{fontSize:25,fontWeight:'700',color:theme.accent},mark:{color:theme.secondary,fontWeight:'700',fontSize:12},card:{padding:15,flexDirection:'row',borderRadius:14,borderWidth:1,borderColor:theme.cardBorder,backgroundColor:theme.cardBg},unread:{borderColor:theme.primary,backgroundColor:theme.selectedBackground},flex:{flex:1},cardTitle:{fontWeight:'700',color:theme.textPrimary},body:{color:theme.textSecondary,marginTop:4},time:{fontSize:10,color:theme.textMuted,marginTop:7},dot:{width:8,height:8,borderRadius:4,backgroundColor:theme.primary},error:{padding:20,gap:12,backgroundColor:theme.cardBg,borderRadius:14,borderWidth:1,borderColor:theme.cardBorder},errorTitle:{fontWeight:'700',color:theme.textPrimary},retry:{alignSelf:'flex-start',paddingHorizontal:18,paddingVertical:10,borderRadius:9,backgroundColor:theme.primaryButtonBackground},retryText:{color:theme.white,fontWeight:'700'}});
