import MaterialIcons from '@expo/vector-icons/MaterialIcons';
import { useEffect, useMemo, useState } from 'react';
import { Modal, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { usePalette, type ThemePalette } from '@/hooks/use-palette';

const valid=/^([01]\d|2[0-3]):([0-5]\d)$/;
const parts=(value:string)=>{const match=value.match(valid);return match?[Number(match[1]),Number(match[2])] as const:[8,0] as const};
const format=(hour:number,minute:number)=>`${String(hour).padStart(2,'0')}:${String(minute).padStart(2,'0')}`;

export function TimePickerField({label,value,onChange,optional=false}:{label:string;value:string;onChange:(value:string)=>void;optional?:boolean}){
 const theme=usePalette(),styles=useMemo(()=>makeStyles(theme),[theme]);
 const[visible,setVisible]=useState(false),[hour,setHour]=useState(parts(value)[0]),[minute,setMinute]=useState(parts(value)[1]);
 useEffect(()=>{if(visible){const next=parts(value);setHour(next[0]);setMinute(next[1])}},[value,visible]);
 const confirm=()=>{onChange(format(hour,minute));setVisible(false)};
 return <View><Text style={styles.label}>{label}</Text><Pressable accessibilityRole="button" accessibilityLabel={`${label}: ${value||'not selected'}`} style={styles.field} onPress={()=>setVisible(true)}><Text style={[styles.value,!value&&styles.placeholder]}>{value||'Select time'}</Text><MaterialIcons name="schedule" size={22} color={theme.primary}/></Pressable><Modal transparent visible={visible} animationType="fade" onRequestClose={()=>setVisible(false)}><View style={styles.modal}><Pressable style={styles.backdrop} onPress={()=>setVisible(false)}/><View style={styles.picker}><Text style={styles.title}>Select time</Text><Text style={styles.preview}>{format(hour,minute)}</Text><View style={styles.columns}><View style={styles.column}><Text style={styles.columnTitle}>Hour</Text><ScrollView style={styles.scroll} nestedScrollEnabled>{Array.from({length:24},(_,item)=><Pressable key={item} style={[styles.option,hour===item&&styles.selected]} onPress={()=>setHour(item)}><Text style={[styles.optionText,hour===item&&styles.selectedText]}>{String(item).padStart(2,'0')}</Text></Pressable>)}</ScrollView></View><Text style={styles.colon}>:</Text><View style={styles.column}><Text style={styles.columnTitle}>Minute</Text><ScrollView style={styles.scroll} nestedScrollEnabled>{Array.from({length:12},(_,item)=>item*5).map(item=><Pressable key={item} style={[styles.option,minute===item&&styles.selected]} onPress={()=>setMinute(item)}><Text style={[styles.optionText,minute===item&&styles.selectedText]}>{String(item).padStart(2,'0')}</Text></Pressable>)}</ScrollView></View></View><View style={styles.actions}>{optional?<Pressable onPress={()=>{onChange('');setVisible(false)}}><Text style={styles.action}>Clear</Text></Pressable>:null}<Pressable onPress={()=>setVisible(false)}><Text style={styles.action}>Cancel</Text></Pressable><Pressable onPress={confirm}><Text style={styles.action}>Set time</Text></Pressable></View></View></View></Modal></View>
}
const makeStyles=(t:ThemePalette)=>StyleSheet.create({label:{fontWeight:'600',color:t.textPrimary,marginBottom:6},field:{height:48,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderWidth:1,borderColor:t.inputBorder,borderRadius:10,paddingHorizontal:12,backgroundColor:t.cardBg},value:{color:t.textPrimary},placeholder:{color:t.placeholder},modal:{flex:1,alignItems:'center',justifyContent:'center',padding:20},backdrop:{...StyleSheet.absoluteFillObject,backgroundColor:'rgba(0,0,0,.55)'},picker:{width:'100%',maxWidth:360,padding:18,borderRadius:16,backgroundColor:t.cardBg,elevation:8},title:{fontSize:18,fontWeight:'700',color:t.primary,textAlign:'center'},preview:{fontSize:32,fontWeight:'700',color:t.accent,textAlign:'center',marginVertical:12},columns:{height:230,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:12},column:{width:92,height:'100%'},columnTitle:{textAlign:'center',color:t.textSecondary,fontWeight:'600',marginBottom:6},scroll:{borderWidth:1,borderColor:t.inputBorder,borderRadius:10,backgroundColor:t.screenBg},option:{height:42,alignItems:'center',justifyContent:'center'},optionText:{color:t.textPrimary},selected:{backgroundColor:t.primary,borderRadius:8},selectedText:{color:t.white,fontWeight:'700'},colon:{fontSize:28,fontWeight:'700',color:t.primary},actions:{minHeight:44,flexDirection:'row',alignItems:'center',justifyContent:'flex-end',gap:20,marginTop:12},action:{color:t.primary,fontWeight:'700'}});
