import MaterialIcons from '@expo/vector-icons/MaterialIcons';
import { useFocusEffect } from '@react-navigation/native';
import { useRouter } from 'expo-router';
import { useCallback, useMemo, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { EmptyState, LoadingState, ScreenContainer } from '@/components/ui/screen-states';
import { CareTokens } from '@/components/ui/care-schedule';
import { QuickAddSheet } from '@/components/ui/quick-add-sheet';
import { getCareSchedule, localDate, medicationProgress } from '@/lib/services/care-schedule';
import { useAuth } from '@/providers/auth-provider';
import type { CareScheduleItem, MedicationDay } from '@/types';

// useBottomTabBarHeight positioning was replaced with useSafeAreaInsets so the FAB sits directly above the tab bar.

export default function CareSchedule(){
 const router=useRouter(),insets=useSafeAreaInsets(),{user,loading:authLoading}=useAuth();
 const[date,setDate]=useState(localDate()),[mode,setMode]=useState<'today'|'history'>('today'),[data,setData]=useState<Awaited<ReturnType<typeof getCareSchedule>>|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[menu,setMenu]=useState(false);
 const load=useCallback(async()=>{if(authLoading)return;if(!user){setLoading(false);setError('Sign in to view your care schedule.');return;}setLoading(true);setError('');try{setData(await getCareSchedule(date));}catch(loadError){if(__DEV__)console.debug('[CareSchedule] Refresh unavailable',{name:loadError instanceof Error?loadError.name:'UnknownError',message:loadError instanceof Error?loadError.message:'Unknown failure'});setError("We couldn't load your schedule.");}finally{setLoading(false);}},[authLoading,date,user]);
 useFocusEffect(useCallback(()=>{void load();},[load]));
 const dates=useMemo(()=>[-2,-1,0,1,2].map(offset=>{const value=new Date();value.setDate(value.getDate()+offset);return value;}),[]);
 const quickAdd=(kind:'medication'|'appointment'|'activity'|'sleep')=>{if(__DEV__)console.debug('[InteractionDebug]',{screen:'CareSchedule',control:`quick-add-${kind}`,disabled:false,loading,modalVisible:menu});setMenu(false);router.push({pathname:{medication:'/add-medication',appointment:'/add-appointment',activity:'/add-activity',sleep:'/add-sleep'}[kind] as '/add-medication',params:{date}})};
 const meds=data?.medications as MedicationDay|undefined,progress=medicationProgress((meds?.items??[]).map(item=>({startsAt:item.log.scheduledFor,status:item.log.status})));
 return <View style={styles.root}><ScreenContainer contentContainerStyle={[styles.content,{paddingBottom:insets.bottom+20}]}>
  <View style={styles.header}><View style={styles.flex}><Text style={styles.title}>Care Schedule</Text><Text style={styles.muted}>Your medications, appointments and activities</Text></View><Pressable accessibilityLabel="Open full calendar" style={styles.calendar} onPress={()=>router.push({pathname:'/care-calendar',params:{date}})}><MaterialIcons name="calendar-month" size={25} color={CareTokens.accent}/></Pressable></View>
  <View style={styles.tabs}>{(['today','history']as const).map(value=><Pressable key={value} style={[styles.tab,mode===value&&styles.activeTab]} onPress={()=>setMode(value)}><Text style={mode===value?styles.activeText:styles.muted}>{value==='today'?'Today':'History'}</Text></Pressable>)}</View>
  {loading||authLoading?<LoadingState label="Loading care schedule..."/>:error?<View accessibilityRole="alert" style={styles.errorCard}><Text style={styles.errorTitle}>{error}</Text><Text style={styles.muted}>Check your connection and try again.</Text><Pressable accessibilityRole="button" accessibilityState={{disabled:false}} style={styles.retry} onPress={()=>{if(__DEV__)console.debug('[InteractionDebug]',{screen:'CareSchedule',control:'retry',disabled:false,loading:false,modalVisible:menu});void load();}}><Text style={styles.retryText}>Try Again</Text></Pressable></View>:<>
   <View style={styles.dateRow}>{dates.map(value=>{const key=localDate(value),selected=key===date;return <Pressable key={key} style={[styles.date,selected&&styles.selectedDate]} onPress={()=>setDate(key)}><Text style={selected?styles.selectedText:styles.muted}>{value.toLocaleDateString([],{weekday:'short'}).toUpperCase()}</Text><Text style={selected?styles.selectedText:styles.dateNumber}>{value.getDate()}</Text></Pressable>})}</View>
   {data?.warnings.length?<View style={styles.warning}><Text style={styles.warningText}>Some schedule information is temporarily unavailable: {data.warnings.map(item=>item.source).join(', ')}.</Text></View>:null}
   {mode==='today'?<><View style={styles.progress}><Text style={styles.progressLabel}>Medication Progress</Text>{progress.percent===null?<Text style={styles.white}>No doses due yet</Text>:<><Text style={styles.percent}>{Math.round(progress.percent)}%</Text><Text style={styles.white}>{progress.takenDueCount} of {progress.dueDoseCount} due doses taken</Text></>}<Text style={styles.progressNote}>{progress.futureDoseCount} scheduled later today. Routine tracking only.</Text></View><Text style={styles.activityText}>{data?.activityGoalMinutes?`${Math.round(Math.min(data.totalActivityMinutes/data.activityGoalMinutes,1)*100)}% of your activity goal • ${data.totalActivityMinutes} minutes`:`${data?.totalActivityMinutes??0} minutes of activity today`}</Text><ScheduleSection title="Today's Schedule" items={data?.items??[]} onPress={item=>item.kind==='medication'?router.push({pathname:'/medication-details',params:{id:item.resourceId}}):item.kind==='appointment'?router.push({pathname:'/appointment-details',params:{id:item.resourceId}}):undefined}/>{!data?.items.length?<EmptyState message="No health activities scheduled for this day."/>:null}{!data?.sleep.length?<Text style={styles.empty}>No sleep data recorded yet.</Text>:null}</>:<><Text style={styles.sectionTitle}>History for {new Date(`${date}T12:00:00`).toLocaleDateString()}</Text><ScheduleSection title="All records" items={(data?.items??[]).filter(item=>item.status!=='pending'||new Date(item.startsAt)<=new Date())}/>{!data?.items.length?<EmptyState message="No history for this date."/>:null}</>}
  </>}
 </ScreenContainer>{!loading&&!error&&user?<Pressable accessibilityLabel="Add to care schedule" style={[styles.fab,{bottom:Math.max(insets.bottom,8)+12}]} onPress={()=>setMenu(true)}><MaterialIcons name="add" size={30} color="#FFF"/></Pressable>:null}<QuickAddSheet visible={menu} onClose={()=>setMenu(false)} onSelect={quickAdd}/></View>;
}
function ScheduleSection({title,items,onPress}:{title:string;items:CareScheduleItem[];onPress?:(item:CareScheduleItem)=>void}){const router=useRouter();return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text>{items.map(item=><Pressable key={item.id} style={styles.card} onPress={()=>item.kind==='activity'?router.push({pathname:'/activity-details',params:{id:item.resourceId}}):onPress?.(item)}><Text style={styles.time}>{new Date(item.startsAt).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</Text><View style={styles.flex}><Text style={styles.cardTitle}>{item.title}</Text><Text style={styles.muted}>{item.subtitle}</Text></View><Text style={styles.status}>{(item.status??item.kind).toUpperCase()}</Text></Pressable>)}</View>}
const styles=StyleSheet.create({root:{flex:1,backgroundColor:CareTokens.background},content:{paddingHorizontal:18,paddingTop:20,gap:18,backgroundColor:CareTokens.background},header:{minHeight:54,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:14},flex:{flex:1},title:{...CareTokens.title,color:CareTokens.accent},muted:{color:'#5B6572',fontSize:12,lineHeight:18},calendar:{width:44,height:44,borderRadius:22,backgroundColor:CareTokens.tint,alignItems:'center',justifyContent:'center'},tabs:{flexDirection:'row',padding:4,backgroundColor:'#E8EDF2',borderRadius:12},tab:{flex:1,minHeight:40,alignItems:'center',justifyContent:'center',borderRadius:9},activeTab:{backgroundColor:'#FFF'},activeText:{color:CareTokens.accent,fontWeight:'700'},dateRow:{flexDirection:'row',gap:7},date:{flex:1,minHeight:62,alignItems:'center',justifyContent:'center',backgroundColor:'#FFF',borderWidth:1,borderColor:CareTokens.border,borderRadius:CareTokens.radius},selectedDate:{backgroundColor:CareTokens.accent},selectedText:{color:'#FFF',fontWeight:'700'},dateNumber:{fontSize:17,fontWeight:'700'},progress:{padding:18,borderRadius:CareTokens.radius,backgroundColor:CareTokens.accent},progressLabel:{color:'#D5E8FF',fontWeight:'700'},white:{color:'#FFF',fontWeight:'600'},percent:{color:'#FFF',fontSize:32,fontWeight:'700'},progressNote:{color:'#D5E8FF',fontSize:10,marginTop:5},activityText:{padding:14,backgroundColor:'#FFF',borderRadius:CareTokens.radius,color:CareTokens.accent,fontWeight:'700'},section:{gap:10},sectionTitle:{fontSize:19,fontWeight:'700',color:'#1A202C'},card:{flexDirection:'row',alignItems:'center',gap:10,padding:14,borderWidth:1,borderColor:CareTokens.border,borderRadius:CareTokens.radius,backgroundColor:'#FFF'},time:{width:62,fontSize:11,fontWeight:'700'},cardTitle:{fontWeight:'700'},status:{fontSize:9,fontWeight:'700',color:CareTokens.accent},empty:{padding:12,color:'#5B6572'},warning:{padding:12,borderRadius:10,backgroundColor:'#FFF4DE'},warningText:{color:'#7A4B00',fontSize:12},errorCard:{padding:20,gap:10,borderRadius:CareTokens.radius,backgroundColor:'#FFF',borderWidth:1,borderColor:CareTokens.border},errorTitle:{fontSize:17,fontWeight:'700',color:'#1A202C'},retry:{alignSelf:'flex-start',paddingHorizontal:18,paddingVertical:11,borderRadius:10,backgroundColor:CareTokens.accent},retryText:{color:'#FFF',fontWeight:'700'},manage:{padding:14,alignItems:'center'},manageText:{color:CareTokens.accent,fontWeight:'700'},fab:{position:'absolute',right:22,width:58,height:58,borderRadius:29,backgroundColor:CareTokens.accent,alignItems:'center',justifyContent:'center',elevation:6}});
